version: '3'
services:
  keepcodein:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app 
    environment:
      - REACT_APP_NAME=ZAKI
      - CHOKIDAR_USEPOLLING=true
    # env_file:
    #   - ./.env

